# Settings for mimir-distributed chart
# -- See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yamlfor available values.
# @default -- Our overrides are defined in charts/values.yaml file.
mimir-distributed:
  cluster:
    name: bigbang
  mimir:
    structuredConfig:
      blocks_storage:
        backend: filesystem

  minio:
    enabled: false
  grafanaAgent:
    enabled: false

  global:
    image:
      pullSecrets:
      - name: private-registry
