# Settings for mimir-distributed chart
# -- See https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/values.yaml for available values.
# @default -- Our overrides are defined in charts/values.yaml file.
mimir-distributed:
  image:
    repository: registry1.dso.mil/ironbank/opensource/grafana/mimir
    tag: 2.14.0
    pullSecrets:
    - private-registry

  global:
    extraVolumes:
    - name: mimir-storage
      emptyDir: {}
    extraVolumeMounts:
    - name: mimir-storage
      mountPath: /tmp/mimir
  
  mimir:
    structuredConfig:
      common:
        storage:
          backend: filesystem
          filesystem:
            dir: /tmp/mimir
      blocks_storage:
        filesystem:
          dir: /tmp/mimir/blocks
      ruler_storage:
        filesystem:
          dir: /tmp/mimir/ruler
      alertmanager_storage:
        filesystem:
          dir: /tmp/mimir/alertmanager
      limits:
      # Minimum limits required for Big Bang
        max_label_names_per_series: 40
        max_global_series_per_user: 300000 # Optionally disable by setting to 0
        out_of_order_time_window: 10s 


  memcached:
    image: 
      repository: registry1.dso.mil/ironbank/opensource/memcached/memcached
      tag: 1.6.31
  
  # Placeholder when image available in IB
  memcachedExporter:
    enabled: false
  #   image: 
  #     repository: registry1.dso.mil/ironbank/opensource/ #TODO
  #     tag: 

  rollout_operator:
    image:
      repository: registry1.dso.mil/ironbank/opensource/grafana/rollout-operator 
      tag: v0.20.0
    imagePullSecrets:
    - name: private-registry
    
  minio:
    enabled: false
  grafanaAgent:
    enabled: false

  nginx: 
    image:
      registry: registry1.dso.mil
      repository: ironbank/opensource/nginx/nginx
      tag: 1.27.2

  # Placeholder when image available in IB
  enterprise:
    enabled: false
  #   image: 
  #     repository: registry1.dso.mil/ironbank/opensource/ #TODO
  #     tag: 
  #     pullPolicy:
  
  gateway:
    enabledNonEnterprise: true
    nginx:
      image:
        registry: registry1.dso.mil
        repository: ironbank/opensource/nginx/nginx
        tag: 1.27.2

networkPolicies:
  # -- Toggle networkPolicies
  enabled: true
  # -- Control Plane CIDR, defaults to 0.0.0.0/0, use `kubectl get endpoints -n default kubernetes` to get the CIDR range needed for your cluster
  # Must be an IP CIDR range (x.x.x.x/x - ideally with /32 for the specific IP of a single endpoint, broader range for multiple masters/endpoints)
  # Used by package NetworkPolicies to allow Kube API access
  controlPlaneCidr: 0.0.0.0/0
  additionalPolicies: []

  egress: {}


istio:
  # -- Toggle istio configuration
  enabled: false
  # -- Default peer authentication values
  hardened:
    enabled: false
    outboundTrafficPolicyMode: "REGISTRY_ONLY"
    customServiceEntries: []
      # - name: "allow-google"
      #   enabled: true
      #   spec:
      #     hosts:
      #       - google.com
      #     location: MESH_EXTERNAL
      #     ports:
      #       - number: 443
      #         protocol: TLS
      #         name: https
      #     resolution: DNS

  mtls:
    # -- STRICT = Allow only mutual TLS traffic,
    # PERMISSIVE = Allow both plain text and mutual TLS traffic
    mode: STRICT

