{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-minio-egress-minio
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - { key: app.kubernetes.io/name, operator: In, values: ["minio"] }
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: mimir
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: minio
    ports:
    - port: 9000
      protocol: TCP
{{- end }}
