{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-ingress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchExpressions:
      - { key: app.kubernetes.io/name, operator: In, values: ["mimir", "rollout-operator"] }
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus 
      namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: monitoring
    ports:
    - port: {{ .Values.serverGrpcListenPort }}
    - port: {{ .Values.serverHttpListenPort}}
{{- end }}

