{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-kube-apiserver-egress-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  {{- range (lookup "v1" "Endpoints" "default" "kubernetes").subsets }}
  - to:
    {{- range .addresses }}
    - ipBlock:
        cidr: {{ .ip }}/32
    {{- end }}
    ports:
      {{- range .ports }}
      - protocol: {{ .protocol }}
        port: {{ .port }}
      {{- end }}
  {{- end }}
{{- end }}