{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-lookups-mimir
spec:
  matchExpressions:
      - { key: app.kubernetes.io/name, operator: In, values: ["mimir", "rollout-operator"] }
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - port: 53
      protocol: TCP
    - port: 53
      protocol: UDP
    {{- if .Values.openshift }}
    - port: 5353
      protocol: TCP
    - port: 5353
      protocol: UDP
    {{- end }}
{{- end }}