{{- if .Values.networkPolicies.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mimir-ingress-grafana
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchExpressions:
      - { key: app.kubernetes.io/name, operator: In, values: ["mimir", "rollout-operator"] }
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        {{- $defaultNSSelector := dict "matchLabels" (dict "app.kubernetes.io/name" "monitoring") -}}
        {{- (dig "grafana" "namespaceSelector" $defaultNSSelector .Values.networkPolicies.egress) | toYaml | nindent 8 }}
    - podSelector:
        {{- $defaultPodSelector := dict "matchLabels" (dict "app.kubernetes.io/name" "grafana") -}}
        {{- (dig "grafana" "podSelector" $defaultPodSelector .Values.networkPolicies.egress) | toYaml | nindent 8 }}
    ports:
    - port: {{ index .Values "upstream" "mimir" "serverHttpListenPort" }}
    - port: {{ index .Values "upstream" "mimir" "serverGrpcListenPort" }}
{{- end }}
