{{- if and .Values.istio.enabled .Values.istio.hardened.enabled .Values.istio.hardened.minioOperator.enabled -}}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: mimir-allow-minio-operator-authz-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: {{ .Values.istio.hardened.minioOperator.namespaces }}
        principals: {{ .Values.istio.hardened.minioOperator.principals }}
{{- end }}