{{- if include "mimir.shouldDeployUpgradeResources" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.upgradeJob.role }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed,before-hook-creation
rules:
- apiGroups: ["minio.min.io",""]
  resources: ["tenants","persistentvolumeclaims","persistentvolumes"]
  verbs: ["get", "list", "delete"]
{{- end }}